package com.company.platform.logging.domain.model;

public enum PiiType {
    GENERIC, NAME, EMAIL, PHONE, ADDRESS, DATE_OF_BIRTH, NATIONAL_ID,
    PASSPORT, TAX_ID, ACCOUNT_NUMBER, CARD_NUMBER, CVV, PIN, USERNAME,
    PASSWORD, TOKEN, API_KEY, CLIENT_SECRET, AUTHORIZATION, COOKIE,
    IP_ADDRESS, GEOLOCATION, DEVICE_ID, BIOMETRIC, HEALTH_DATA, FINANCIAL_DATA
}
