server:
  address: ${TEST_APP_BIND_ADDRESS:127.0.0.1}
  port: ${CACHE_TEST_APP_PORT:18081}

spring:
  application:
    name: platform-cache-test-app

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always


platform:
  core:
    openapi:
      enabled: true
      title: Platform Integration Test
      version: 1.0.0
      description: Platform Integration Test API
      authentication-type:
  cache:
    enabled: true
    annotations-enabled: true
    application: ${spring.application.name}
    environment: ${APP_ENVIRONMENT:local}
    defaults:
      ttl: 10m
      key-prefix: platform-cache-test
      cache-null-values: false
      key-hash-enabled: true
      maximum-entry-size: 1048576
    stores:
      caffeine-default:
        provider: CAFFEINE
        caffeine:
          maximum-size: 1000
          expire-after-write: 10m
          record-stats: true
      caffeine-l1:
        provider: CAFFEINE
        caffeine:
          maximum-size: 500
          expire-after-write: 30s
          record-stats: true
      caffeine-l2:
        provider: CAFFEINE
        caffeine:
          maximum-size: 2000
          expire-after-write: 5m
          record-stats: true
      redis-l3:
        provider: REDIS
        redis:
          mode: STANDALONE
          host: ${CACHE_REDIS_HOST:localhost}
          port: ${CACHE_REDIS_PORT:6379}
          database: ${CACHE_REDIS_DATABASE:0}
          client-name: platform-cache-test-app
          password: ${CACHE_REDIS_PASSWORD:aloaluale}
          command-timeout: 2s
          connect-timeout: 2s
          shutdown-timeout: 2s
          serialization:
            key: STRING
            value: JSON
            value-envelope-enabled: true
            schema-id: cache-test-app
            schema-version: 1
    caches:
      demo-caffeine:
        store: caffeine-default
        ttl: 10m
        failure-policy: FAIL_CLOSED
        key:
          version: v1
          sensitive: true
      demo-redis:
        store: redis-l3
        ttl: 10m
        failure-policy: FAIL_CLOSED
        key:
          version: v1
          sensitive: true
      demo-three-level-l1:
        store: caffeine-l1
        ttl: 30s
        failure-policy: FAIL_CLOSED
        key:
          version: v1
          sensitive: true
      demo-three-level-l2:
        store: caffeine-l2
        ttl: 5m
        failure-policy: FAIL_CLOSED
        key:
          version: v1
          sensitive: true
      demo-three-level-l3:
        store: redis-l3
        ttl: 10m
        failure-policy: FAIL_CLOSED
        key:
          version: v1
          sensitive: true
    observability:
      metrics-enabled: true
      health-enabled: true
      events-enabled: true
      local-hit-observation-enabled: true
      log-cache-key: HASH
      log-cache-value: false
