# New
platform:
  cache:
    enabled: true
    provider: redis
spring:
  cache:
    redis:
      time-to-live: 3600
      use-key-prefix: true
      key-prefix: "${spring.application.name}:"
      customize:
        cache-test:
          ttl: 60

  data:
    redis:

      database: 0
      password: ENC(8npBK18k4dDSAgCV0hlmMMi/FSgBxF5362SwMDCJNtccbk7zCcEVA/F22ZiOL0De)
      sentinel:
        master: mymaster
        nodes:
            - ${REDIS_SENTINEL_HOST:localhost}:${REDIS_SENTINEL_PORT:26379}
        password: ENC(8npBK18k4dDSAgCV0hlmMMi/FSgBxF5362SwMDCJNtccbk7zCcEVA/F22ZiOL0De)

      connect-timeout: 3s
      timeout: 3s

      lettuce:
        cluster:
          refresh:
            dynamic-refresh-sources: true
            period: 30s

        pool:
          enabled: true

jasypt:
  encryptor:
    password: haicut12102001@
