platform:
  queue:
    enabled: true
    provider: kafka

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:19092}
    client-id: platform-integration
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 10
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        spring.json.add.type.headers: false
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      enable-auto-commit: false
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: com.company.platform.integration.queue.internal.domain
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.company.platform.integration.queue.internal.domain.QueueDemoEvent
    listener:
      ack-mode: manual_immediate
      missing-topics-fatal: true
      observation-enabled: true
    template:
      observation-enabled: true
    admin:
      fail-fast: true

logging:
  level:
    com.company.platform.queue: ${PLATFORM_QUEUE_LOG_LEVEL:DEBUG}
    com.company.platform.integration.queue: ${INTEGRATION_QUEUE_LOG_LEVEL:DEBUG}
