platform:
  core:
    openapi:
      enabled: true
      title: Platform Integration Test
      version: 1.0.0
      description: Platform Integration Test API
      authentication-type: JWT
    web:
      request-logging-enabled: true
