spring:
  application:
    name: platform-integration-test
  profiles:
    group:
      common: core, logging, client, cache
      local: common
    active: local

logging:
  level:
    root: INFO
    com.company.platform: INFO

management:
  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        enabled: false
  endpoints:
    web:
      exposure:
        include: health,info,metrics
